CLASS zcl_class_a_apack_base DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
  " Changes from local
ENDCLASS.



CLASS zcl_class_a_apack_base IMPLEMENTATION.
ENDCLASS.
