CLASS zcl_class_b_apack_base DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
  " Changes from Github
ENDCLASS.



CLASS zcl_class_b_apack_base IMPLEMENTATION.
ENDCLASS.
